

# IN MARIO FOLDER WE ARE TRYING TO CREATE THE BUILDING BLOCKS OF THE MARIO GAME 
# FIRST WE ARE BUILDING HEIGHT IN THE FOLDER heightcol folder IN THE FORM OF HASHTAGS (#)
# SECOND WE ARE BUILDING THE COLLUMNS IN WIDTH IN THE FOLDER widthcol IN THE FORM OF QUESTION MARKS (?) 
# THIRD WE ARE BUILDING
